sudo: false
language: "python"
python:
  - "3.5"
install:
  - "pip3 install -U pip"  # upgrade pip
  - "git clone https://github.com/sirfoga/pyhal"
  - "cd pyhal"
  - "pip3 install ."  # run local setup (pyhal)
  - "cd .."  # return to root folder
  - "pip3 install ."  # run local setup
script:
  - "python3 setup.py test"
notifications:
  email: "false"  # no email notify
